### ISSUE TITLE
Non-italic version & No red

### ISSUE THREAD

**Issue by nohwnd** [Spriie/sl33pyTheme#1]
I really like the colors, and the theme overall, but could you make a version that does not use italics? 

And also one more request, could you consider not using red at all? Red usually signals error, so I might be more sensitive to it. So for example in `C#` it makes for quite a jarring experience, because the least important parts are highlighted by the most important color.

![image](https://user-images.githubusercontent.com/5735905/55060621-2cd28a00-5072-11e9-8113-fa9be8c40ebf.png)

_The icon is really cute btw, is that your own design? :)_

**Comment by Spriie** [comment]
Thanks for the suggestions. I have changed the red syntax highlighting to a pale peach. Italics have been removed but I may make an italic variant down the road. Please send any more suggestions you . have :).
